require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CustomerService::TicketsController do

  # This should return the minimal set of attributes required to create a valid
  # CustomerService::Ticket. As you add validations to CustomerService::Ticket, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "body" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # CustomerService::TicketsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all customer_service_tickets as @customer_service_tickets" do
      message = CustomerService::Ticket.create! valid_attributes
      get :index, {}, valid_session
      assigns(:customer_service_tickets).should eq([message])
    end
  end

  describe "GET show" do
    it "assigns the requested customer_service_ticket as @customer_service_ticket" do
      message = CustomerService::Ticket.create! valid_attributes
      get :show, {:id => message.to_param}, valid_session
      assigns(:customer_service_ticket).should eq(message)
    end
  end

  describe "GET new" do
    it "assigns a new customer_service_ticket as @customer_service_ticket" do
      get :new, {}, valid_session
      assigns(:customer_service_ticket).should be_a_new(CustomerService::Ticket)
    end
  end

  describe "GET edit" do
    it "assigns the requested customer_service_ticket as @customer_service_ticket" do
      message = CustomerService::Ticket.create! valid_attributes
      get :edit, {:id => message.to_param}, valid_session
      assigns(:customer_service_ticket).should eq(message)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CustomerService::Ticket" do
        expect {
          post :create, {:customer_service_ticket => valid_attributes}, valid_session
        }.to change(CustomerService::Ticket, :count).by(1)
      end

      it "assigns a newly created customer_service_ticket as @customer_service_ticket" do
        post :create, {:customer_service_ticket => valid_attributes}, valid_session
        assigns(:customer_service_ticket).should be_a(CustomerService::Ticket)
        assigns(:customer_service_ticket).should be_persisted
      end

      it "redirects to the created customer_service_ticket" do
        post :create, {:customer_service_ticket => valid_attributes}, valid_session
        response.should redirect_to(CustomerService::Ticket.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved customer_service_ticket as @customer_service_ticket" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerService::Ticket.any_instance.stub(:save).and_return(false)
        post :create, {:customer_service_ticket => { "body" => "invalid value" }}, valid_session
        assigns(:customer_service_ticket).should be_a_new(CustomerService::Ticket)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerService::Ticket.any_instance.stub(:save).and_return(false)
        post :create, {:customer_service_ticket => { "body" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested customer_service_ticket" do
        message = CustomerService::Ticket.create! valid_attributes
        # Assuming there are no other customer_service_tickets in the database, this
        # specifies that the CustomerService::Ticket created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CustomerService::Ticket.any_instance.should_receive(:update_attributes).with({ "body" => "MyText" })
        put :update, {:id => message.to_param, :customer_service_ticket => { "body" => "MyText" }}, valid_session
      end

      it "assigns the requested customer_service_ticket as @customer_service_ticket" do
        message = CustomerService::Ticket.create! valid_attributes
        put :update, {:id => message.to_param, :customer_service_ticket => valid_attributes}, valid_session
        assigns(:customer_service_ticket).should eq(message)
      end

      it "redirects to the customer_service_ticket" do
        message = CustomerService::Ticket.create! valid_attributes
        put :update, {:id => message.to_param, :customer_service_ticket => valid_attributes}, valid_session
        response.should redirect_to(message)
      end
    end

    describe "with invalid params" do
      it "assigns the customer_service_ticket as @customer_service_ticket" do
        message = CustomerService::Ticket.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerService::Ticket.any_instance.stub(:save).and_return(false)
        put :update, {:id => message.to_param, :customer_service_ticket => { "body" => "invalid value" }}, valid_session
        assigns(:customer_service_ticket).should eq(message)
      end

      it "re-renders the 'edit' template" do
        message = CustomerService::Ticket.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CustomerService::Ticket.any_instance.stub(:save).and_return(false)
        put :update, {:id => message.to_param, :customer_service_ticket => { "body" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested customer_service_ticket" do
      message = CustomerService::Ticket.create! valid_attributes
      expect {
        delete :destroy, {:id => message.to_param}, valid_session
      }.to change(CustomerService::Ticket, :count).by(-1)
    end

    it "redirects to the customer_service_tickets list" do
      message = CustomerService::Ticket.create! valid_attributes
      delete :destroy, {:id => message.to_param}, valid_session
      response.should redirect_to(customer_service_tickets_url)
    end
  end

end
