安徽省:
  sf: 18.0
  zt: 8.0
北京市:
  sf: 18.0
  zt: 8.0
福建省:
  sf: 18.0
  zt: 8.0
甘肃省:
  sf: 18.0
  zt: 8.0
广东省:
  sf: 12.0
  zt: 6.0
广西壮族自治区:
  sf: 18.0
  zt: 8.0
贵州省:
  sf: 18.0
  zt: 8.0
海南省:
  sf: 18.0
  zt: 8.0
河北省:
  sf: 18.0
  zt: 8.0
河南省:
  sf: 18.0
  zt: 8.0
黑龙江省:
  sf: 18.0
  zt: 8.0
湖北省:
  sf: 18.0
  zt: 8.0
湖南省:
  sf: 18.0
  zt: 8.0
吉林省:
  sf: 18.0
  zt: 8.0
江苏省:
  sf: 18.0
  zt: 8.0
江西省:
  sf: 18.0
  zt: 8.0
辽宁省:
  sf: 18.0
  zt: 8.0
内蒙古自治区:
  sf: 18.0
  zt: 8.0
宁夏回族自治区:
  sf: 18.0
  zt: 8.0
青海省:
  sf: 18.0
  zt: 8.0
山东省:
  sf: 18.0
  zt: 8.0
山西省:
  sf: 18.0
  zt: 8.0
陕西省:
  sf: 18.0
  zt: 8.0
上海市:
  sf: 18.0
  zt: 8.0
四川省:
  sf: 18.0
  zt: 8.0
天津市:
  sf: 18.0
  zt: 8.0
西藏自治区:
  sf: 18.0
  zt: 8.0
新疆维吾尔自治区:
  sf: 18.0
  zt: 8.0
云南省:
  sf: 18.0
  zt: 8.0
浙江省:
  sf: 18.0
  zt: 8.0
重庆市:
  sf: 18.0
  zt: 8.0
香港:
  sf: 28.0
  zt: 8.0
澳门:
  sf: 18.0
  zt: 8.0
