---
:concurrency: 4
:pidfile: tmp/pids/sidekiq.pid
staging:
  :concurrency: 10
production:
  :concurrency: 20
:queues:
  - notifications
  - devise
  - mails
  - mailers
  - default
  - elasticsearch
  - edm
  - waybill
  - weekly
:limits:
  waybill: 1
  weekly: 1
  edm: 10
