require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LandingPagesController do

  # This should return the minimal set of attributes required to create a valid
  # LandingPage. As you add validations to LandingPage, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "theme" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LandingPagesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all landing_pages as @landing_pages" do
      landing_page = LandingPage.create! valid_attributes
      get :index, {}, valid_session
      assigns(:landing_pages).should eq([landing_page])
    end
  end

  describe "GET show" do
    it "assigns the requested landing_page as @landing_page" do
      landing_page = LandingPage.create! valid_attributes
      get :show, {:id => landing_page.to_param}, valid_session
      assigns(:landing_page).should eq(landing_page)
    end
  end

  describe "GET new" do
    it "assigns a new landing_page as @landing_page" do
      get :new, {}, valid_session
      assigns(:landing_page).should be_a_new(LandingPage)
    end
  end

  describe "GET edit" do
    it "assigns the requested landing_page as @landing_page" do
      landing_page = LandingPage.create! valid_attributes
      get :edit, {:id => landing_page.to_param}, valid_session
      assigns(:landing_page).should eq(landing_page)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new LandingPage" do
        expect {
          post :create, {:landing_page => valid_attributes}, valid_session
        }.to change(LandingPage, :count).by(1)
      end

      it "assigns a newly created landing_page as @landing_page" do
        post :create, {:landing_page => valid_attributes}, valid_session
        assigns(:landing_page).should be_a(LandingPage)
        assigns(:landing_page).should be_persisted
      end

      it "redirects to the created landing_page" do
        post :create, {:landing_page => valid_attributes}, valid_session
        response.should redirect_to(LandingPage.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved landing_page as @landing_page" do
        # Trigger the behavior that occurs when invalid params are submitted
        LandingPage.any_instance.stub(:save).and_return(false)
        post :create, {:landing_page => { "theme" => "invalid value" }}, valid_session
        assigns(:landing_page).should be_a_new(LandingPage)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        LandingPage.any_instance.stub(:save).and_return(false)
        post :create, {:landing_page => { "theme" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested landing_page" do
        landing_page = LandingPage.create! valid_attributes
        # Assuming there are no other landing_pages in the database, this
        # specifies that the LandingPage created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        LandingPage.any_instance.should_receive(:update).with({ "theme" => "MyString" })
        put :update, {:id => landing_page.to_param, :landing_page => { "theme" => "MyString" }}, valid_session
      end

      it "assigns the requested landing_page as @landing_page" do
        landing_page = LandingPage.create! valid_attributes
        put :update, {:id => landing_page.to_param, :landing_page => valid_attributes}, valid_session
        assigns(:landing_page).should eq(landing_page)
      end

      it "redirects to the landing_page" do
        landing_page = LandingPage.create! valid_attributes
        put :update, {:id => landing_page.to_param, :landing_page => valid_attributes}, valid_session
        response.should redirect_to(landing_page)
      end
    end

    describe "with invalid params" do
      it "assigns the landing_page as @landing_page" do
        landing_page = LandingPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LandingPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => landing_page.to_param, :landing_page => { "theme" => "invalid value" }}, valid_session
        assigns(:landing_page).should eq(landing_page)
      end

      it "re-renders the 'edit' template" do
        landing_page = LandingPage.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        LandingPage.any_instance.stub(:save).and_return(false)
        put :update, {:id => landing_page.to_param, :landing_page => { "theme" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested landing_page" do
      landing_page = LandingPage.create! valid_attributes
      expect {
        delete :destroy, {:id => landing_page.to_param}, valid_session
      }.to change(LandingPage, :count).by(-1)
    end

    it "redirects to the landing_pages list" do
      landing_page = LandingPage.create! valid_attributes
      delete :destroy, {:id => landing_page.to_param}, valid_session
      response.should redirect_to(landing_pages_url)
    end
  end

end
